---
- hosts: all
  name: Install Cobalt Strike
  become: yes
  become_method: sudo
  roles:
    - openjdk
    - role: cobalt_strike
      vars:
        bucket_name: "{{ build_bucket }}"
    - server_setup
  tasks:
    - name: Install Thunderbird mail client and dnsutils
      ansible.builtin.package:
        name:
          - dnsutils
          - thunderbird
    - name: Install python3-boto3 for Teamserver cloud-init scripts
      ansible.builtin.package:
        name:
          - python3-boto3
    - name: Install some Cobalt Strike addons
      block:
        - name: Install CobaltStrike-Toolkit
          ansible.builtin.import_role:
            name: assessment_tool
          vars:
            archive_src: "https://github.com/killswitch-GUI/\
            CobaltStrike-Toolkit/tarball/master"
            install_dir: /tools/CobaltStrike-Toolkit
            powershell: yes
            unarchive_extra_opts:
              - --strip-components=1
        - name: Install Malleable-C2-Profiles
          ansible.builtin.import_role:
            name: assessment_tool
          vars:
            archive_src: "https://github.com/rsmudge/Malleable-C2-Profiles/\
            tarball/master"
            install_dir: /tools/Malleable-C2-Profiles
            unarchive_extra_opts:
              - --strip-components=1
        - name: Install Malleable-C2-Randomizer
          ansible.builtin.import_role:
            name: assessment_tool
          vars:
            archive_src: "https://github.com/bluscreenofjeff/\
            Malleable-C2-Randomizer/tarball/master"
            install_dir: /tools/Malleable-C2-Randomizer
            unarchive_extra_opts:
              - --strip-components=1
      vars:
        # Group ownership for the Cobalt Strike addons
        group: wheel
    - name: Install libreoffice
      ansible.builtin.package:
        name:
          - libreoffice
