---
- hosts: all
  name: Install Cobalt Strike
  become: yes
  become_method: sudo
  roles:
    - openjdk
    - role: cobalt_strike
      vars:
        bucket_name: "{{ build_bucket }}"
    - server_setup
  tasks:
    - name: Install Thunderbird mail client and dnsutils
      ansible.builtin.package:
        name:
          - dnsutils
          - thunderbird
    - name: Install python3-boto3 for Teamserver cloud-init scripts
      ansible.builtin.package:
        name:
          - python3-boto3
