---
- hosts: all
  name: Install Cobalt Strike
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Install OpenJDK
      ansible.builtin.include_role:
        name: openjdk
    - name: Install Cobalt Strike
      ansible.builtin.include_role:
        name: cobalt_strike
      vars:
        cobalt_strike_bucket_name: "{{ build_bucket }}"
    - name: Install ServerSetup script
      ansible.builtin.include_role:
        name: server_setup
    - name: Install dnsutils
      ansible.builtin.package:
        name:
          - dnsutils
    # install-certificates.py provides the certificate that is in turn
    # used by add-https-certificate-block-to-cs-profiles.sh
    - name: >
        Install python3-boto3 for Teamserver cloud-init script
        install-certificates.py
      ansible.builtin.package:
        name:
          - python3-boto3
    - name: Install some Cobalt Strike addons
      vars:
        # Group ownership for the Cobalt Strike addons
        #
        # Note that this means that the vnc.yml playbook _must_ run
        # before this one, so that the wheel group has been created.
        group: wheel
      block:
        # This tool requires a JRE, but we have already installed one
        # above
        - name: Install C2concealer
          ansible.builtin.include_role:
            name: assessment_tool
          vars:
            assessment_tool_archive_src: "https://github.com/FortyNorthSecurity/\
            C2concealer/tarball/master"
            assessment_tool_install_dir: /tools/C2concealer
            assessment_tool_pip_extra_args: "--editable"
            assessment_tool_pip_packages:
              - .
            assessment_tool_unarchive_extra_opts:
              - --strip-components=1
        - name: Install CobaltStrike-Toolkit
          ansible.builtin.include_role:
            name: assessment_tool
          vars:
            assessment_tool_archive_src: "https://github.com/killswitch-GUI/\
            CobaltStrike-Toolkit/tarball/master"
            assessment_tool_install_dir: /tools/CobaltStrike-Toolkit
            assessment_tool_powershell: true
            assessment_tool_unarchive_extra_opts:
              - --strip-components=1
        - name: Install Malleable-C2-Profiles
          ansible.builtin.include_role:
            name: assessment_tool
          vars:
            assessment_tool_archive_src: "https://github.com/rsmudge/\
            Malleable-C2-Profiles/tarball/master"
            assessment_tool_install_dir: /tools/Malleable-C2-Profiles
            assessment_tool_unarchive_extra_opts:
              - --strip-components=1
        - name: Install Malleable-C2-Randomizer
          ansible.builtin.include_role:
            name: assessment_tool
          vars:
            assessment_tool_archive_src: "https://github.com/bluscreenofjeff/\
            Malleable-C2-Randomizer/tarball/master"
            assessment_tool_install_dir: /tools/Malleable-C2-Randomizer
            assessment_tool_unarchive_extra_opts:
              - --strip-components=1
        - name: Install SourcePoint
          ansible.builtin.include_role:
            name: assessment_tool
          vars:
            assessment_tool_archive_src: https://github.com/Tylous/SourcePoint/tarball/main
            assessment_tool_go: true
            assessment_tool_install_dir: /tools/SourcePoint
            assessment_tool_unarchive_extra_opts:
              - --strip-components=1
