---
- name: Import AWS playbook
  ansible.builtin.import_playbook: aws.yml

- name: Import base image playbook
  ansible.builtin.import_playbook: base.yml

- name: Import UFW playbook
  ansible.builtin.import_playbook: ufw.yml

- name: Import Cobalt Strike and related tools playbook
  ansible.builtin.import_playbook: cobalt_strike.yml

- name: Import Cobalt Strike add-ons playbook
  ansible.builtin.import_playbook: cobalt_strike_addons.yml

- name: Import additional software playbook
  ansible.builtin.import_playbook: additional_software.yml

# The AWS playbook must run before this one, since this playbook uses
# a user group created in the AWS playbook.
- name: Import VNC playbook
  ansible.builtin.import_playbook: vnc.yml

- name: Import cloud-init playbook
  ansible.builtin.import_playbook: cloud_init.yml
