---
- hosts: all
  name: Install VNC and configure VNC user
  become: yes
  become_method: ansible.builtin.sudo
  tasks:
    - name: Install VNC
      ansible.builtin.include_role:
        name: vnc_server
      vars:
        # The user information and ssh keys for the VNC user
        vnc_server_password: "{{ lookup('aws_ssm', '/vnc/password') }}"
        vnc_server_private_ssh_key: |-
          {{ lookup('aws_ssm', '/vnc/ssh/ed25519_private_key') }}
        vnc_server_public_ssh_key: |-
          {{ lookup('aws_ssm', '/vnc/ssh/ed25519_public_key') }}
        vnc_server_user_groups:
          # Note that this means that the aws.yml playbook _must_ run
          # before this one, so that the efs_users group has been
          # created.
          - efs_users
        # Note that we use the same UID for the VNC and Samba guest
        # users on all instances.  This helps us avoid UID/GID
        # collisions with files written to the EFS share.
        vnc_server_user_uid: 2048
    - name: Add VNC user to wheel group
      block:
        - name: Ensure wheel group exists
          ansible.builtin.group:
            name: wheel
        - name: Give wheel group passwordless sudo access
          ansible.builtin.copy:
            content: |
              %wheel ALL=(ALL:ALL) NOPASSWD: ALL
            dest: /etc/sudoers.d/passwordless-sudo-for-wheel
            mode: 0444
        - name: Add VNC user to wheel group
          ansible.builtin.user:
            append: yes
            groups:
              - wheel
            name: "{{ vnc_server_username }}"
    # These environment variables were asked for in
    # cisagov/cool-system#212
    - name: Add PCA-specific environment variables
      ansible.builtin.lineinfile:
        create: yes
        group: "{{ vnc_server_username }}"
        line: "{{ item }}"
        mode: 0644
        owner: "{{ vnc_server_username }}"
        path: /home/{{ vnc_server_username }}/.bashrc
      loop:
        - export EFS_SHARE=/share
        - export PCA_OPS_PATH=${EFS_SHARE}/PCA
        - export PCA_DEV_PATH=${EFS_SHARE}/private
  vars:
    # The username for the VNC user
    vnc_server_username: "{{ lookup('aws_ssm', '/vnc/username') }}"
